# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  domain_name: example.com
  secret_key_base: 9d6f872b1f9ada4dbfe568ce8648577e8627d3bcefb65f616fcabb5e0d2f2ccd5a09a9c2e473a7975f92d18eecc1a677d867054e789866d9908a68c705c77267
  omniauth_provider_key: <%= ENV["OMNIAUTH_PROVIDER_KEY"] %>
  omniauth_provider_secret: <%= ENV["OMNIAUTH_PROVIDER_SECRET"] %>
  orcid_omniauth_provider_key: <%= ENV["ORCID_OMNIAUTH_PROVIDER_KEY"] %>
  orcid_omniauth_provider_secret: <%= ENV["ORCID_OMNIAUTH_PROVIDER_SECRET"] %>
  domain_name: example.com
  secret_key_base: (not shown)
  
test:
  secret_key_base: 3ebf54e9eaacadc083956a922c2f71b8b23552ac8014a7578de8874032b6a1c8bc4cf85c7dd51b9db7aff71206d2d27f2c35b349996b6ef7e05a35f4a3a7e30d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  domain_name: <%= ENV["DOMAIN_NAME"] %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  omniauth_provider_key: <%= ENV["OMNIAUTH_PROVIDER_KEY"] %>
  omniauth_provider_secret: <%= ENV["OMNIAUTH_PROVIDER_SECRET"] %>
  orcid_omniauth_provider_key: <%= ENV["ORCID_OMNIAUTH_PROVIDER_KEY"] %>
  orcid_omniauth_provider_secret: <%= ENV["ORCID_OMNIAUTH_PROVIDER_SECRET"] %>